# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
enable_free_tier: true
tone_instructions: "Be concise and focus on critical issues only"
reviews:
  poem: false
  profile: chill
  review_status: false
  changed_files_summary: false
  estimate_code_review_effort: false
  request_changes_workflow: true
  high_level_summary: false
  auto_review:
    enabled: true
    auto_incremental_review: true
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  sequence_diagrams: false
  pre_merge_checks:
    docstrings:
      mode: "off"
    title:
      mode: "off"
    description:
      mode: "off"
    issue_assessment:
      mode: "off"
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "DEVELOPMENT.md"
      - "CONTRIBUTING.md"
      - "AGENTS.md"
      - "src/pdf_toolbox/AGENTS.md"
      - "scripts/AGENTS.md"
      - "tests/AGENTS.md"
